spring.application.name=octomind-api

spring.datasource.url=jdbc:postgresql://localhost:5432/octomind
spring.datasource.username=octomind
spring.datasource.password=octomind

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true